Refactor find.turn.point.R and find.tol.time.R
RECETOX/recetox-aplcms-archive pull request #91
Opened 2022-08-08 09:01 UTC by wverastegui

Refactored  find.tol.time.R and find.turn.point.R. The pastecs library has been added to use the Turnpoint function in find.turn.point.R, that simplifies the code.

2022-08-11 09:38 UTC, wverastegui commented
find.turn.pint.R was reverted to refactored version, Turnpoint function prevents passing the tests. Changelog file was updated accordingly (96c64aed9afc5aa6bbe68b4e8e3f03829548da1e)

2022-08-11 10:02 UTC, hechth commented on conda/meta.yaml
> +    - r-pastecs
Please remove this from meta.yaml

2022-08-11 10:02 UTC, hechth commented on conda/environment-dev.yaml
> +  - r-pastecs
```suggestion
```

2022-08-11 10:02 UTC, hechth commented on conda/meta.yaml
> +    - r-pastecs
```suggestion
```

2022-08-11 10:34 UTC, xtrojak requested changes
Consider spending more time with the merge, I think the final version could benefit from both your and my refactored versions.

2022-08-12 06:25 UTC, hechth commented on DESCRIPTION
> +        iterators, snow, gbm, e1071, randomForest, ROCR, ROCS, Rcpp, dplyr, tidyr, stringr, tibble, pastecs, tools, arrow
```suggestion
        iterators, snow, gbm, e1071, randomForest, ROCR, ROCS, Rcpp, dplyr, tidyr, stringr, tibble, tools, arrow
```

2022-08-12 06:29 UTC, hechth commented
> Consider spending more time with the merge, I think the final version could benefit from both your and my refactored versions.

Thanks for the hint - I'll have a better look and see how to merge it better! Thanks for paying attention to details :)

2022-08-17 07:05 UTC, xtrojak approved these changes

2022-08-17 07:05 UTC, xtrojak commented on R/find.tol.time.R
> +    # rt_tol_relative <- x[sel]
```suggestion
```

2022-08-17 07:06 UTC, merged